apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: pod-security-policy
spec:
  privileged: false
  allowPrivilegeEscalation: false
  requiredDropCapabilities:
    - ALL
  volumes:
  - configMap
  - downwardAPI
  - emptyDir
  - persistentVolumeClaim
  - secret
  - projected
  hostNetwork: false
  hostIPC: false
  hostPID: false
  runAsUser:
    rule: MustRunAsNonRoot
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  readOnlyRootFilesystem: true


# apiVersion: policy/v1beta1
# kind: PodSecurityPolicy
# metadata:
#   name: example-pod-security-policy
# spec:
#   privileged: false
#   allowPrivilegeEscalation: false
#   hostIPC: false
#   hostNetwork: false
#   hostPID: false
#   volumes:
#   - configMap
#   - downwardAPI
#   - emptyDir
#   - persistentVolumeClaim
#   - secret
#   - projected
#   runAsUser:
#     rule: MustRunAsNonRoot
#   fsGroup:
#     rule: MustRunAs
#     ranges:
#     - min: 1
#       max: 65535
