apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dev-pod-reader
  namespace: dev-namespace
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - configmaps
  verbs:
  - get
  - list
  - delete
  - update
  - create
  - watch

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-pod-security-policy
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - pod-security-policy
